apiVersion: v1
kind: Secret
metadata:
  name: taskmgmt-secret
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.postgres.password | quote }}
  password: {{ .Values.postgres.password | quote }}
  SECRET_KEY: {{ .Values.userService.secretKey | quote }}